export enum ToolbarButton {
  DASHBOARD = 'dashboard',
  REPORTS = 'REPORTS',
  PROJECTS = 'PROJECTS',
  USERS = 'USERS',
  ATTENDANCE = 'ATTENDANCE',
  TIMESHEET_APPROVAL = 'TIMESHEET_APPROVAL',
  MY_SANDBOX = 'MY_SANDBOX'
}
